### ISSUE TITLE
Clefairy isn't type "Normal" though

### ISSUE THREAD

**Issue by pcordon** [nisargkolhe/Battlepedia-for-Pokemon-Go#6]
Hey, 

Great app. However I don't think it's complete or accurate. I've noticed several errors in how Pokemon are classified, especially their type. Like the title says, for instance.

**Comment by nisargkolhe** [comment]
Fixed in the latest version!

**Comment by pcordon** [comment]
Thank you for your response. I noticed the APK version is the same I downloaded a long time ago. Did the version number remain the same after your update? Thank you again.

**Comment by nisargkolhe** [comment]
The latest version is v1.1.0, you should have v1.0.0 installed right now.

**Comment by pcordon** [comment]
How would I go about installing 1.1.0 then? The main page shows a link to the old 1.0.0 only. Cheers.

**Comment by nisargkolhe** [comment]
Sorry, forgot to update the Readme. 😅Just for the reference, latest releases are always posted first on the "Releases" section here - https://github.com/nisargkolhe/Battlepedia-for-Pokemon-Go/releases

**Comment by pcordon** [comment]
Thank you @nisargkolhe!
